# Generated by Django 3.1.3 on 2020-11-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
    ]
