# Generated by Django 3.1.3 on 2020-11-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
