# Generated by Django 3.1.3 on 2020-11-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='title',
        ),
    ]
