# Generated by Django 3.1.3 on 2020-11-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_auto_20201116_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=True),
            preserve_default=False,
        ),
    ]
