# Generated by Django 3.1.3 on 2020-11-19 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_image_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pub_date',
        ),
    ]
